import datetime


FEE_TRANSFERS = [
    {
        'result_amount': 80,
        'old_result_amount': 82,
        'source': {'key': 'source_a', 'title': 'Source A'},
        'created_at': datetime.datetime(2025, 1, 15, 10, 30),
        'fee_history': {
            'key': 1,
            'title': 'Fee history 1',
        },
        'history_name': 'Service fee',
        'history_accrual_type': 1,
        'history_percent_part': False,
        'history_percent': 0.5,
        'history_fix_part': False,
        'history_created_at': datetime.datetime(2025, 1, 10, 9, 0),
        'history_source': 'Source A',
        'history_payment_systems': 'System A',
        'history_operation_type': 'rule_a',
    },
    {
        'result_amount': 125,
        'old_result_amount': 130,
        'source': {'key': 'source_b', 'title': 'Source B'},
        'created_at': datetime.datetime(2025, 2, 20, 11, 45),
        'fee_history': {'key': 2, 'title': 'Fee history 2'},
        'history_name': 'Processing fee',
        'history_accrual_type': 2,
        'history_percent_part': True,
        'history_percent': 1.250,
        'history_fix_part': False,
        'history_created_at': datetime.datetime(2025, 2, 1, 8, 15),
        'history_source': 'Source B',
        'history_payment_systems': 'System B',
        'history_operation_type': 'rule_b',
    },
    {
        'result_amount': 45,
        'old_result_amount': 45,
        'source': {'key': 'source_c', 'title': 'Source C'},
        'created_at': datetime.datetime(2025, 3, 25, 14, 0),
        'fee_history': {'key': 3, 'title': 'Fee history 3'},
        'history_name': 'Additional fee',
        'history_accrual_type': 3,
        'history_percent_part': False,
        'history_percent': 0,
        'history_fix_part': True,
        'history_created_at': datetime.datetime(2025, 3, 1, 12, 0),
        'history_source': 'Source C',
        'history_payment_systems': 'System C',
        'history_operation_type': 'rule_c',
    },
]
