name: brilliance

services:
  backend:
    build:
      context: ./../..
      dockerfile: .configs/docker/Dockerfile
    volumes:
      - ./../../:/app

      - backend_venv:/app/.venv
      - uv_cache:/root/.cache/uv
      - uv_python:/root/.local/share/uv

      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:delegated
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:delegated
    environment:
      POSTGRES_DB: brilliance
      POSTGRES_USER: brilliance
      POSTGRES_PASSWORD: brilliance
      POSTGRES_HOST: postgres
    tmpfs:
      - /tmp
    ports:
      - 8082:8082
    command: uv run uvicorn example.main:app --host 0.0.0.0 --port 8082 --reload --proxy-headers --forwarded-allow-ips='*'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      start_period: 30s
      start_interval: 2s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: brilliance
      POSTGRES_USER: brilliance
      POSTGRES_PASSWORD: brilliance
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432', '-U', 'brilliance']
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  backend_venv:
  uv_cache:
  uv_python:
