name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build containers
        run: docker compose -f .configs/docker/docker-compose.yml build

      - name: Run tests
        run: docker compose -f .configs/docker/docker-compose.yml run --rm backend sh -c 'uv sync --all-groups --all-extras && uv run pytest'


  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/example
            git pull
            docker compose -f .configs/docker/docker-compose.yml pull
            docker compose -f .configs/docker/docker-compose.yml up -d --build
