name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Run tests
        run: uv run pytest

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Debug vars
        run: |
          echo "HOST=${{ vars.SERVER_HOST }}"
          echo "USER=${{ vars.SERVER_USER }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rsync -avz --delete ./build/ ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:/var/www/html
